languageCode = "en-gb"
title = "Tom's corner of the internet"
baseurl = "/"
theme = "bare"
enableGitInfo = true

[params]
mainSections = ["posts"]
author = "Tom Forbes"
email = "tom@tomforb.es"
repoLink = "https://github.com/orf/blog-hugo"
description = 'Python developer living and working in London'
includeAuthorInTitle = true

[[params.social]]
icon = "github"
url = "https://github.com/orf/"

[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/in/tom-forbes"

[permalinks]
posts = ":slug/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'colorful'
tabWidth = 4


[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
[privacy.youtube]
privacyEnhanced = true
