[build]
environment = { HUGO_VERSION = "0.67.1" }
command = "git submodule update --init --recursive --depth=1 && hugo --minify"

[context.deploy-preview]
command = "git submodule update --init --recursive --depth=1 && hugo -b $DEPLOY_PRIME_URL --minify"
